---
- name: Packages
  hosts: all
  tasks:
    - name: Install the nodejs LTS repos
      epel_repository:
        unarchive:
          src: http://www.yourmirror.com/centos/python/Python-3.6.4-binary.tar.gz dest=/tmp/Python-3.6.4-binary.tar.gz
          dest: /tmp

    - name: Install the nodejs
      yum:
        name: 
        - wget
        - 
        state: installed
    - name: Installing package manager

